services:
    localstack:
        container_name: "localstack_main"
        image: localstack/localstack:latest
        environment: 
            - SERVICES=dynamodb,lambda,kinesis
            - DEFAULT_REGION=ap-southeast-2
            - DOCKER_HOST=unix:///var/run/docker.sock 
            - DEBUG=1
            - DATA_DIR=/var/lib/localstack/data
            - PORT_WEB_UI=8080
            - LAMBDA_DOCKER_NETWORK=localstack-tutorial
            - KINESIS_PROVIDER=kinesalite
        ports:
            - "4566:4566"
            - "4571:4571"
            - "8080:8080"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./data:/var/lib/localstack/data
        networks:
            - default
   
networks:
    default:
        name: localstack-tutorial